# Generated by Django 4.0.1 on 2022-01-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='programs',
            field=models.ManyToManyField(blank=True, to='core.Program'),
        ),
    ]
