# Generated by Django 4.0.1 on 2022-02-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coupon_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
    ]
