# Generated by Django 4.0.1 on 2022-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programenrollment',
            name='role',
            field=models.IntegerField(choices=[(0, 'student'), (1, 'instructor'), (2, 'maintainer')], default=0),
        ),
    ]
